server:
  port: 9003

#Spring
spring:
  jpa:
    show-sql: 'true'
  h2:
    console:
      enabled: 'true'
  datasource:
    sql-script-encoding: 'UTF-8'

#Actuator Config
management:
  endpoints:
    web:
      exposure:
        include: 'refresh'

#Eureka
eureka:
  client:
    registerWithEureka: 'true'
    fetchRegistry: 'true'
    serviceUrl:
      defaultZone: 'http://localhost:9102/eureka/'