#Spring
spring:
  application:
    name: 'microservice-produits'
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: 'none'
    database-plateform: 'org.hibernate.dialect.H2Dialect'
  h2:
    console:
      enable: 'true'
  sql:
    init:
      mode: 'never'
  datasource:
    url: 'jdbc:h2:mem:testdb'
    driverClassName: 'org.h2.Driver'
    username: 'sa'
    password: ''
    sql-script-encoding: 'UTF-8'

#Personal config
mes-configs:
  limitDeProduits: 5

#Actuator conf
management:
  endpoints:
    web:
      exposure:
        include: 'refresh'

#Eureka
eureka:
  client:
    registerWithEureka: 'true'
    fetchRegistry: 'true'
    serviceUrl:
      defaultZone: 'http://localhost:9102/eureka/'

#Configurations H2
#spring.jpa.show-sql=true
#spring.h2.console.enabled=true
#spring.jpa.hibernate.ddl-auto=none
#spring.sql.init.mode=never

#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#Nos configurations
#mes-configs.limitDeProduits=5

#Actuator Config
#management.endpoints.web.exposure.include=refresh

#défini l'encodage pour data.sql
#spring.datasource.sql-script-encoding=UTF-8

#Eureka
#eureka.client.serviceUrl.defaultZone: http://localhost:9102/eureka/